### ISSUE TITLE
Error 500 when searching for packages

### ISSUE THREAD

**Issue by dustinsoftware** [chriseldredge/Klondike#47]
The following URL causes the service to throw an exception:

http://nuget/nuget/Search()?$filter=IsLatestVersion%20or%20IsAbsoluteLatestVersion&$orderby=(DownloadCount%20gt%20300)%20and%20(substringof(%27foo%27,Title)%20or%20substringof(%27foo%27,Id))%20desc,DownloadCount%20desc&$top=20&searchTerm=%27foo%27&targetFramework=%27%27&includePrerelease=true

```
2014-08-15 09:23:41,530 ERROR  22 UnhandledExceptionLogger System.Data.Services.IDataService.InternalHandleException System.InvalidCastException: Unable to cast object of type 'System.Linq.Expressions.SimpleBinaryExpression' to type 'System.Linq.Expressions.MemberExpression'.
   at Lucene.Net.Linq.LuceneQueryModel.AddSort(Expression expression, OrderingDirection direction)
   at Lucene.Net.Linq.Translation.QueryModelTranslator.VisitOrderByClause(OrderByClause orderByClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Lucene.Net.Linq.Translation.QueryModelTranslator.Build(QueryModel queryModel)
   at Lucene.Net.Linq.LuceneQueryExecutorBase`1.PrepareQuery(QueryModel queryModel)
   at Lucene.Net.Linq.LuceneQueryExecutorBase`1.<ExecuteCollection>d__3`1.MoveNext()
   at System.Data.Services.DataService`1.SerializeResponseBody(RequestDescription description, IDataService dataService)
   at System.Data.Services.DataService`1.HandleRequest()
```

We are running version 0.9.0.

**Comment by piers7** [comment]
I was having the same problem, also from Linqpad.
Problem goes away if you change the 'Sort By' column in linqpad to something other than 'relevance', which presumably then generates a simpler (or at least lucene-compliant) order by in the odata.

**Comment by chriseldredge** [comment]
Has someone reported this issue to the Linqpad support team? I have a feeling this type of ordering clause, even if it works with NuGet Gallery today, is non-standard and likely to cause problems. I would argue that Linqpad should not be trying to influence the order of results in such a complicated way and that the server that hosts the packages is probably better informed about the relevance of fuzzy search results.

**Comment by piers7** [comment]
Yes, I raised a bug with Linqpad support. But I'll forward your comments to him too.
